#ifndef __SSL_WIFI_CONFIG_H
#define __SSL_WIFI_CONFIG_H

#define SSL_WIFI_SSID     "YOUR_5G_WIFI_SSID"
#define SSL_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define SSL_WIFI_TCP_PORT 9000
#define SSL_UART_BAUDRATE 921600

#define SSL_UART_RX_PIN 12
#define SSL_UART_TX_PIN 11

#endif /* __SSL_WIFI_CONFIG_H */
